team24 update
GDSC-YU/website pull request #19
Opened 2024-09-22 12:05 UTC by ez76z

I made a new team section with an empty structure and roles.

2024-09-22 14:25 UTC, Shaar03 commented on src/data/teams/team24.ts
adding this file is not enough
check en.json, ar.json, and TeamButton.svelte

2024-09-23 08:43 UTC, Shaar03 commented
please run the project locally to test it out.
<img width="539" alt="buttons" src="https://github.com/user-attachments/assets/0c7ae94e-9a68-4816-8d28-30d55c96a5bc">
this isn't what we expect, there must be only one button for viewing teams.
a button for the events section is also missing

2024-10-04 22:12 UTC, g9wz requested changes
make sure to have the proper extensions to format your files before pushing

2024-10-04 22:12 UTC, g9wz commented on .vscode/launch.json
remove this

2024-10-04 22:12 UTC, g9wz commented on src/lib/events/ui/EventsButton.svelte
make this a dropdown, this is bad ux

2024-10-04 22:12 UTC, g9wz commented on src/lib/team/parts/TeamButton.svelte
same here, should be dropdown not a button

2024-10-04 22:12 UTC, g9wz commented on src/locales/en.json
> +	"Club": "Groups",
make the arabic version consistent to this or the other way around

you can't be a student club in arabic but not in english

2024-10-04 22:12 UTC, g9wz commented on src/routes/+page.svelte
> +	const title = 'Google DG | Al Yamamah';
It's GDG "on Campus"

2024-10-04 22:12 UTC, g9wz commented on src/routes/+page.svelte
also it would be nice if you can localize the meta tags too

i'm pretty sure svelte-i18n is SEO friendly, check their docs

2024-10-05 16:00 UTC, Shaar03 submitted a review, later dismissed

2024-11-04 14:16 UTC, merged